---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCBspUgc9Oo3Ts3Uzuau6lahFmXcyTVzbpJrk9qIGmTn6qwh663oO2JTGTiJc4+itzMlT7021p9QD7l/p5MNZUrm+ZnMYTr7oANXI+jP8py5jAbO7xxp3yGQrAT1dp6BpdJtsUeIypRLj2eZ8pLlOLRBAdKthkTvQY1cN78G5SG8G3rTOdnN7OzSilUy+QwFoh40pPvl4OjmNa4DQ68IqdbSr8oA0yX7I+7yYnz1KtaVfvTMgTDd+nlkp7zn8mSPjmHWwGkneG4TToWIRtaGybW20aEF0YFMr3m+p1O19pFYwWSrXgUjWY8na8FctO5yiNY5Er9G4OYX0lnjzs5P6A4VZh+BOoUvd6XNyuO5WTIIOJwSo4RO8IkadeFTJaRkai1M3lqfCJ6ahNWPaf7B49mt9xU9XPwDo9NfbVbBrlfOhH26YEMwSWHPTY/iWvR67AnaWiGLUUWpc7zMNZp4KhLlUl8caGpdtz5XhISqkc/hX/ribVfybFu1C+Q02Vd4QWeRmGC8aLmrtop8NTgFo3izoDP/RQTOCPpSShzp1Sh0Jp5cRZ4ERoTsNNFJlX3CeAWRdI4LHoZQqAowGNCGdw9SgBf9OHq4yVwvoTMwuu7ZBEMKldYyB/lZqgRZAKfve29nsvdQDiCGNEEPfcJnyvrJJ8psvHU2DJTShRMK7OWNpspxiCCzcLcLTqg43dF1UmL
  template:
    metadata:
      name: grafana-credentials
      namespace: monitoring
