---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: default
spec:
  encryptedData:
    password: AgB/eoygdS9GOJEpWlKNUumaOgaNiMIlF/w+T6LYVO436wDaM9eROadmA/ABVng5PKN1gAI3x/LW0rZH/7sykxKAC/RlG/57ou9Kok8zeC02SSDmrvDZPT0zDklfJj5qHW+7rR8aSdDK4Vuh1xseluXPGzqnEHrXbXwXOi16f6mq88j/bLRM7FgwTXjHLQlcnYxoS8A59zgXo4mHcbI0n9A7OR8ng180zuEEF7bBEj/rkI++OuZivd9mqFhKX1YdbFjowFRrkqkJSaNTPmLM8mQpCb38nrHPtySlMhJvXFOghY3dQ0w4Ql7tzLJHjXyziWBLp/ONH7ZZZBcnXf+u44H6A/ybb3+5Ei9bS4KhRKwoQLOZhVlOnFEmbjLkcrvrOsTmPL69CIxyY2JBi2MUIw06pYXWUaymXYt2Lm8WKsfQT8OU0INeVtdgy6LV22y/f1P0+15FMzGUyFyX+wYwCNZzfJcdIozVCijK8qDy/DQtttXFrqNKOKUN1uj4muCwpspK6dv+SXWnF17SxCQZNf0jgyZmVp+43TBRle6Ur5XZmtwKy7twZmMTQatltLavFHc9eG8igOPkDrIc1VQRHqHH9hMYOe8pPt/16j4tlhzqhBhZwXipfQcHk/+KwfBJ3ZjuLOBXB+iSYfunqOPXOIh0R6ZzHtPgwpMmsxLdeRhliANz5uENH5xFxVKqU4oKZRJUbNN8dgxWOA==
    postgres-password: AgB7wo8gnhbGiGoUlYaJmvfVp8Js2mivHjbN48TS1qAiYQA5ta3jAK29qLdCegTeQk4nCl1s39VNyl7opobam33uxHAPgYoEaOh/BmLfzczGQzW5OEovALSY9CzFSgOXTEiX05b3QVgtHsKP+dgrSC8AVm2Wsd0vwG50tW3ho8+7XwJLjKiKr75f4ntWarfzGcC24D6PY9iuBV+8OXIQUV9F8oHg6Gf8cDb6dpq8DgfhiKTdNY9yI9ifoga1yFwAsKOvl0Rz707DnBe4By2ykNb9ZuuKasQS3CrtBpegvVXFOY5JKKtfogNr5lh99LqP/M7g7N60TU3Tp7LfXLKSmoNsYj6z3vQ31P1pRSa1f/6AhjfsI48qSe/9l7+5hrGK+vbya8qifEZN3FQz7ml1cKhNGkVfmGl04BhkOGTyXF6jX0XpQfFVRV/uL2tEPKTSPIaqOtI05ZPhXJ/79bZDl1QjA7MAoz49yMTZlwSZVTu8IyJLJei3k4H2kPh+e677uzYpHDYnLlB9xsFlv8rc62vIqm7+U3HV8W9k/IGzBvpsqUKp0IPus5tOc241TL+EL03kRS+W9DrnzIE6PkirxIo3qnJSMsfNfO5YB/YOcMJetoJSvQ31pQeY3pZTje8vcLiyikjLl+8ZU2Q6AHlvUPaekiAWWEDW5QfgPrzGTu5/fj3YqU6+5w1nR9ocUktWrmIEb6US1jPp+g==
  template:
    metadata:
      name: postgres-credentials
      namespace: default
    type: Opaque
