apiVersion: batch/v1
kind: CronJob
metadata:
  name: kyverno-sentinel
  namespace: kyverno-sentinel
  labels:
    app: kyverno-sentinel
spec:
  schedule: "*/15 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: kyverno-sentinel
        spec:
          serviceAccountName: kyverno-sentinel
          restartPolicy: OnFailure
          containers:
            - name: kyverno-sentinel
              image: bitnami/kubectl:1.28.0
              command:
                - sh
                - -c
                - |
                  cp /scripts/health-check.sh /tmp/health-check.sh && chmod +x /tmp/health-check.sh && /tmp/health-check.sh
              volumeMounts:
                - name: script
                  mountPath: /scripts
          volumes:
            - name: script
              configMap:
                name: kyverno-sentinel-script
          imagePullPolicy: IfNotPresent
