apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-bootstrap
  namespace: gitops
spec:
  project: default
  source:
    repoURL: https://github.com/youtmaj11/k3slab.git
    targetRevision: HEAD
    path: k8s/security/kyverno/kyverno-app
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
