---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-credentials
  namespace: default
spec:
  encryptedData:
    redis-password: AgAmd0iKrq1hsxlPDgp1ZTM1Mk58L/fp4t/4u24pYb2v7iyySfmq9iRolkDKzAInO1w1DPnwQDS4FofaWEc01N9y2v1OKCmXc84ttLxEj805rDxr7zAkcDzfeGdugvRuSAoFGffxCp4zsHHg9qdvy79p3tynl8ClKgtcvJoFLZkKgsvVdmwO4enVFrhHhgJGGDugYv0Aw6/LGqySDJgQHLgVDiOkHWIQWL4USAQH5gRA9QeptGxtvRYHndmm4lJm0FuGjU96sVUJfSo8nNiybjbWRnH64IS6SMMxT27EepB/po0fherXPyy3VsPIfKuMqBG+fEFbTKOLG+oznLA/Q3vCpbEWb5LKRqxa7ISMycczKzAdipnGt4k0x+orCXIMrzAWmp4DRssxK/vHnDeb+06uFpzoZ+oGUZZKLuKHIIFlRgGCVPMPgOUu73blGZVerefXep3DCGXQMfHNY+VpwisRHXHK0wFkDUHV9NcJO+/xokZWGsWbHztnv/f6zidW5Q7/J2lhF9g9bMuE9sQf6uqie1eUtvsjrBSpFRjLD/aWD2tvaPDSRwM10paY/GtVo8UyriaLQWdqQXt3scNNfqMNePnQlm7iYf0hk74hqeeHoAY240YOGy7ft5WiLB8pyRPSEbNmK3wzrLEAWVShGtyQv0UDXF/dUEIyfMFZC+gfWnY1C0oYRr6KLb77XKPBNKFvwX645/NQ2qatrGc4l3VO
  template:
    metadata:
      name: redis-credentials
      namespace: default
