apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: app-skeleton-hpa
  namespace: default
  labels:
    app: app-skeleton
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-skeleton
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
